import { CroissantDataset } from "./croissant.js";

export enum CdifProfile { DISCOVERY = "https://cdif.codata.org/profile/discovery", MANIFEST = "https://cdif.codata.org/profile/manifest", DATA_DESCRIPTION = "https://cdif.codata.org/profile/data-description", DATA_ACCESS = "https://cdif.codata.org/profile/data-access", ACCESS_RIGHTS = "https://cdif.codata.org/profile/access-rights", CONTROLLED_VOCABULARIES = "https://cdif.codata.org/profile/controlled-vocabularies", DATA_INTEGRATION = "https://cdif.codata.org/profile/data-integration", UNIVERSALS = "https://cdif.codata.org/profile/universals", PROVENANCE = "https://cdif.codata.org/profile/provenance" }
export interface CdifDistribution { id: string; name: string; contentUrl: string; encodingFormat: string }
export interface CdifDataElement { id: string; name: string; dataType: string; description: string; semanticType?: string; recordSet: string }
export interface CdifAccessRights { license: string; policyId?: string; rightsStatement?: string; odrlPolicy?: Record<string, unknown> }

export class CdifResource {
  datasetId: string; title: string; description: string; profiles: CdifProfile[]; landingPage: string; accessService: string; distributions: CdifDistribution[]; dataElements: CdifDataElement[]; accessRights?: CdifAccessRights; temporalCoverage?: string; spatialCoverage?: string; units: string[]; vocabularies: string[]; keywords: string[];
  constructor(init: { datasetId: string; title: string; description: string; profiles: CdifProfile[]; landingPage: string; accessService: string; distributions?: CdifDistribution[]; dataElements?: CdifDataElement[]; accessRights?: CdifAccessRights; temporalCoverage?: string; spatialCoverage?: string; units?: string[]; vocabularies?: string[]; keywords?: string[] }) { Object.assign(this, init); this.distributions ??= []; this.dataElements ??= []; this.units ??= []; this.vocabularies ??= []; this.keywords ??= []; }
  static fromCroissant(dataset: CroissantDataset, landingPage: string, accessService: string): CdifResource {
    const dataElements = dataset.recordSets.flatMap((recordSet) => recordSet.fields.map((field) => ({ id: `${recordSet.id}/field/${field.name}`, name: field.name, dataType: field.dataType, description: field.description, semanticType: field.semanticTypeValue, recordSet: recordSet.id })));
    return new CdifResource({ datasetId: dataset.id, title: dataset.name, description: dataset.description, profiles: Object.values(CdifProfile).filter((p) => p !== CdifProfile.PROVENANCE), landingPage, accessService, distributions: dataset.files.map((f) => ({ id: f.id, name: f.name, contentUrl: f.contentUrl, encodingFormat: f.encodingFormat })), dataElements, accessRights: { license: dataset.license, rightsStatement: "Access and usage must satisfy the attached ODRL/TypeSec policy before agent use." }, vocabularies: dataElements.flatMap((e) => e.semanticType ? [e.semanticType] : []), keywords: dataset.keywords });
  }
  withOdrlPolicy(policyId: string, policy: Record<string, unknown>): CdifResource { return new CdifResource({ ...this, accessRights: { ...(this.accessRights ?? { license: "" }), policyId, odrlPolicy: policy } }); }
  toJsonLd(): Record<string, unknown> { return { "@context": { cdif: "https://cdif.codata.org/", dcat: "http://www.w3.org/ns/dcat#", dct: "http://purl.org/dc/terms/", odrl: "http://www.w3.org/ns/odrl/2/" }, "@type": "dcat:Dataset", "@id": this.datasetId, "dct:title": this.title, "dct:description": this.description, "cdif:profile": this.profiles, "dcat:landingPage": this.landingPage, "dcat:accessService": { "@type": "dcat:DataService", endpointURL: this.accessService }, "dcat:distribution": this.distributions.map((d) => ({ "@type": "dcat:Distribution", "@id": d.id, "dct:title": d.name, "dcat:downloadURL": d.contentUrl, "dcat:mediaType": d.encodingFormat })), "cdif:dataElement": this.dataElements.map((e) => ({ "@type": "cdif:DataElement", "@id": e.id, "dct:title": e.name, "dct:description": e.description, "cdif:dataType": e.dataType, "cdif:semanticType": e.semanticType ?? null, "cdif:recordSet": e.recordSet })), "dct:accessRights": this.accessRights ? { "@type": "dct:RightsStatement", "@id": this.accessRights.policyId ?? null, "dct:license": this.accessRights.license, "dct:description": this.accessRights.rightsStatement ?? null, "odrl:policy": this.accessRights.odrlPolicy ?? null } : null, "dct:temporal": this.temporalCoverage ?? null, "dct:spatial": this.spatialCoverage ?? null, "cdif:unit": this.units, "cdif:controlledVocabulary": this.vocabularies, "dcat:keyword": this.keywords }; }
}
