import { CroissantDataset } from "./croissant.js";
export const SUPPORTED_DIALECTS = new Set(["ANSI_SQL", "SAIL_SQL", "SNOWFLAKE", "MDX", "TABLEAU", "DATABRICKS", "MAQL"]);
export const FALLBACK_DIALECTS = ["ANSI_SQL", "SAIL_SQL"] as const;
export interface OsiAiContextInit { instructions?: string; synonyms?: string[]; examples?: string[] }
export class OsiAiContext { instructions?: string; synonyms: string[]; examples: string[]; constructor(init: string | OsiAiContextInit = {}) { const value = typeof init === "string" ? { instructions: init } : init; this.instructions = value.instructions; this.synonyms = value.synonyms ?? []; this.examples = value.examples ?? []; } static coerce(value: unknown): OsiAiContext | undefined { if (value == null) return undefined; return value instanceof OsiAiContext ? value : new OsiAiContext(value as string | OsiAiContextInit); } }
export interface OsiDialectExpressionInit { dialect: string; expression: string }
export class OsiExpression { dialects: OsiDialectExpressionInit[]; constructor(dialects: OsiDialectExpressionInit[] = []) { this.dialects = dialects; } forDialect(dialect: string): string | undefined { const map = new Map(this.dialects.map((e) => [e.dialect, e.expression])); for (const candidate of [dialect, ...FALLBACK_DIALECTS]) { const expression = map.get(candidate); if (expression) return expression; } return undefined; } }
export interface OsiFieldInit { name: string; description?: string; semanticType?: string; expression?: OsiExpression; aiContext?: OsiAiContext | string; isTimeDimension?: boolean }
export class OsiField { name: string; description?: string; semanticType?: string; expression?: OsiExpression; aiContext?: OsiAiContext; isTimeDimension: boolean; constructor(init: OsiFieldInit) { this.name = init.name; this.description = init.description; this.semanticType = init.semanticType; this.expression = init.expression; this.aiContext = OsiAiContext.coerce(init.aiContext); this.isTimeDimension = init.isTimeDimension ?? false; } get synonyms(): string[] { return this.aiContext?.synonyms ?? []; } }
export interface OsiDatasetInit { name: string; source: string; description?: string; aiContext?: OsiAiContext | string; primaryKey?: string[]; uniqueKeys?: string[][]; fields?: OsiField[] }
export class OsiDataset { name: string; source: string; description?: string; aiContext?: OsiAiContext; primaryKey: string[]; uniqueKeys: string[][]; fields: OsiField[]; constructor(init: OsiDatasetInit) { this.name = init.name; this.source = init.source; this.description = init.description; this.aiContext = OsiAiContext.coerce(init.aiContext); this.primaryKey = init.primaryKey ?? []; this.uniqueKeys = init.uniqueKeys ?? []; this.fields = init.fields ?? []; } get synonyms(): string[] { return this.aiContext?.synonyms ?? []; } }
export class OsiMetric { name: string; expression: OsiExpression; description?: string; aiContext?: OsiAiContext; constructor(init: { name: string; expression: OsiExpression; description?: string; aiContext?: OsiAiContext | string }) { this.name = init.name; this.expression = init.expression; this.description = init.description; this.aiContext = OsiAiContext.coerce(init.aiContext); } get synonyms(): string[] { return this.aiContext?.synonyms ?? []; } }
export interface OsiRelationship { name: string; from: string; to: string; fromColumns: string[]; toColumns: string[] }
export interface OsiOntologyTerm { id: string; label: string; source?: string }
export class OsiSemanticModel { name: string; description?: string; aiContext?: OsiAiContext; datasets: OsiDataset[]; relationships: OsiRelationship[]; metrics: OsiMetric[]; ontologyTerms: OsiOntologyTerm[]; customExtensions: Record<string, unknown>[]; constructor(init: { name: string; description?: string; aiContext?: OsiAiContext | string; datasets?: OsiDataset[]; relationships?: OsiRelationship[]; metrics?: OsiMetric[]; ontologyTerms?: OsiOntologyTerm[]; customExtensions?: Record<string, unknown>[] }) { this.name = init.name; this.description = init.description; this.aiContext = OsiAiContext.coerce(init.aiContext); this.datasets = init.datasets ?? []; this.relationships = init.relationships ?? []; this.metrics = init.metrics ?? []; this.ontologyTerms = init.ontologyTerms ?? []; this.customExtensions = init.customExtensions ?? []; } resolveMetric(name: string, dialect = "SAIL_SQL"): string { const metric = this.metrics.find((candidate) => candidate.name === name); const expression = metric?.expression.forDialect(dialect); if (!expression) throw new Error(`No metric ${name} with an expression for dialect ${dialect}`); return expression; } findBySynonym(term: string): Record<string, string>[] { const needle = term.trim().toLowerCase(); const out: Record<string, string>[] = []; for (const dataset of this.datasets) { if (dataset.name.toLowerCase() === needle || dataset.synonyms.some((s) => s.toLowerCase() === needle)) out.push({ kind: "dataset", name: dataset.name }); for (const field of dataset.fields) if (field.name.toLowerCase() === needle || field.synonyms.some((s) => s.toLowerCase() === needle)) out.push({ kind: "field", name: field.name, dataset: dataset.name }); } for (const metric of this.metrics) if (metric.name.toLowerCase() === needle || metric.synonyms.some((s) => s.toLowerCase() === needle)) out.push({ kind: "metric", name: metric.name }); return out; } }
export class OsiDocument { version: string; semanticModel: OsiSemanticModel; constructor(init: { version?: string; semanticModel: OsiSemanticModel }) { this.version = init.version ?? "0.2.0.dev0"; this.semanticModel = init.semanticModel; } static fromMapping(value: Record<string, unknown>): OsiDocument { const raw = value.semantic_model ?? value.semanticModel; if (Array.isArray(raw)) { if (raw.length !== 1) throw new Error("Multi-model OSI documents are not supported"); return new OsiDocument({ version: String(value.version ?? "0.2.0.dev0"), semanticModel: OsiDocument.modelFromMapping(raw[0] as Record<string, unknown>) }); } return new OsiDocument({ version: String(value.version ?? "0.2.0.dev0"), semanticModel: OsiDocument.modelFromMapping(raw as Record<string, unknown>) }); } static modelFromMapping(value: Record<string, unknown>): OsiSemanticModel { return new OsiSemanticModel({ name: String(value.name), description: value.description as string | undefined, datasets: ((value.datasets ?? []) as Record<string, unknown>[]).map((d) => new OsiDataset({ name: String(d.name), source: String(d.source), description: d.description as string | undefined, fields: ((d.fields ?? []) as Record<string, unknown>[]).map((f) => new OsiField({ name: String(f.name), description: f.description as string | undefined, semanticType: f.semantic_type as string | undefined, aiContext: typeof f.ai_context === "string" ? f.ai_context : undefined })) })), metrics: ((value.metrics ?? []) as Record<string, unknown>[]).map((m) => new OsiMetric({ name: String(m.name), expression: new OsiExpression(((m.expression as Record<string, unknown>)?.dialects ?? []) as OsiDialectExpressionInit[]), description: m.description as string | undefined })) }); } static fromCroissant(dataset: CroissantDataset, modelName?: string, sailSchema = "qg_lakehouse"): OsiDocument { const fields = dataset.recordSets.flatMap((r) => r.fields.map((f) => new OsiField({ name: f.name, description: f.description, semanticType: f.semanticTypeValue, expression: new OsiExpression([{ dialect: "SAIL_SQL", expression: `\`${f.name}\`` }]) }))); const safeName = dataset.name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "") || "dataset"; return new OsiDocument({ semanticModel: new OsiSemanticModel({ name: modelName ?? `${safeName}_semantic_model`, description: `OSI model derived from Semantic Croissant dataset ${dataset.name}.`, aiContext: "Resolve user intent to ontology terms, then map those terms to Croissant fields and governed Sail columns.", datasets: [new OsiDataset({ name: safeName, source: `sail.${sailSchema}.${safeName}`, description: dataset.description, fields })], ontologyTerms: fields.flatMap((f) => f.semanticType ? [{ id: f.semanticType, label: f.name, source: "semantic-croissant" }] : []) }) }); } }
