import { canonicalJson } from "./canonical.js";
import { Ed25519Signer, sha256Hex, unsignedDigest, verify, SIGNATURE_PREFIX } from "./crypto.js";
import { DidDocument } from "./did.js";
import { toToolSchema } from "./agents.js";
export const TYPEDID_PROFILE = "ed25519-x25519-chacha20";
export interface AccessReceipt { principal: string; resource: string; action: string; allowed: boolean; reason: string; policyId?: string; issuedAt: string }
export function signingPayloadV1(sender: string, recipient: string, action: string, resource: string, payloadSha256: string): string { return ["querygraph-typedid-signing-v1", sender, recipient, action, resource, payloadSha256].join("\n"); }
export class TypeDidEnvelope { protocol = "querygraph.typedid.v1"; conversationId: string; sender: string; recipient: string; action: string; resource: string; privacy: string; profile: string; contentType: string; payload: Record<string, unknown>; payloadSha256: string; signature: string; verificationMethod?: string; envelopeDigest: string; createdAt: string;
  private constructor(init: { conversationId: string; sender: string; recipient: string; action: string; resource: string; privacy: string; profile: string; contentType: string; payload: Record<string, unknown>; payloadSha256: string; signature: string; verificationMethod?: string; envelopeDigest: string }) { Object.assign(this, init); this.createdAt = new Date().toISOString(); }
  static create(init: { sender: DidDocument | string; recipient: DidDocument | string; action: string; resource: string; payload: Record<string, unknown>; conversationId?: string; contentType?: string; privacy?: string; profile?: string; signer?: Ed25519Signer }): TypeDidEnvelope { const sender = typeof init.sender === "string" ? init.sender : init.sender.id; const recipient = typeof init.recipient === "string" ? init.recipient : init.recipient.id; const payloadSha256 = sha256Hex(canonicalJson(init.payload)); const conversationId = init.conversationId ?? `qg:${payloadSha256.slice(0, 16)}`; const signing = signingPayloadV1(sender, recipient, init.action, init.resource, payloadSha256); const signature = init.signer?.sign(signing) ?? unsignedDigest(signing); const verificationMethod = init.signer?.verificationMethod(); const envelopeDigest = `sha256:${sha256Hex(["querygraph-typedid-envelope-digest-v1", conversationId, init.privacy ?? "secret", init.profile ?? TYPEDID_PROFILE, signature].join("\n"))}`; return new TypeDidEnvelope({ conversationId, sender, recipient, action: init.action, resource: init.resource, privacy: init.privacy ?? "secret", profile: init.profile ?? TYPEDID_PROFILE, contentType: init.contentType ?? "application/json", payload: init.payload, payloadSha256, signature, verificationMethod, envelopeDigest }); }
  signingPayload(): string { return signingPayloadV1(this.sender, this.recipient, this.action, this.resource, this.payloadSha256); }
  verifyPayload(): boolean { return this.payloadSha256 === sha256Hex(canonicalJson(this.payload)); }
  verifySignature(publicKey?: string | Uint8Array): boolean { return this.verifyPayload() && this.signature.startsWith(SIGNATURE_PREFIX) && verify(publicKey ?? this.verificationMethod!, this.signingPayload(), this.signature); }
  isSigned(): boolean { return this.signature.startsWith(SIGNATURE_PREFIX); }
  toJson(): Record<string, unknown> { return { protocol: this.protocol, conversation_id: this.conversationId, sender: this.sender, recipient: this.recipient, action: this.action, resource: this.resource, privacy: this.privacy, profile: this.profile, content_type: this.contentType, payload: this.payload, payload_sha256: this.payloadSha256, signature: this.signature, verification_method: this.verificationMethod ?? null, envelope_digest: this.envelopeDigest, created_at: this.createdAt }; }
}
export class GovernedPrompt { constructor(public readonly question: string, public readonly semanticContext: Record<string, unknown>, public readonly allowedSources: string[] = [], public readonly deniedSources: string[] = [], public readonly receipts: AccessReceipt[] = []) {} }
export class TypeDidAgent { private constructor(public readonly name: string, public readonly did: DidDocument, private readonly seed: string, public readonly capabilities: string[] = []) {} static new(name: string, seed = `querygraph-agent:${name}`): TypeDidAgent { return new TypeDidAgent(name, DidDocument.newOyd(seed, name), seed); } signer(): Ed25519Signer { return Ed25519Signer.fromSeed(this.seed); } didKey(): string { return this.signer().didKey(); } toToolSchema(flavor: "openai" | "anthropic" = "openai"): Record<string, unknown> { return toToolSchema(this, flavor); } request(recipient: TypeDidAgent, action: string, resource: string, payload: Record<string, unknown>): TypeDidEnvelope { return TypeDidEnvelope.create({ sender: this.did, recipient: recipient.did, action, resource, payload, signer: this.signer() }); } }
export function evaluatePolicy(subject: string, action: string, resource: string, policy: { rules: { action: string; resource: string; subjects: string[] }[] }): AccessReceipt { const allowed = policy.rules.some((rule) => rule.action === action && rule.resource === resource && (rule.subjects.length === 0 || rule.subjects.includes(subject))); return { principal: subject, resource, action, allowed, reason: allowed ? "policy allows action" : "no matching permission", issuedAt: new Date().toISOString() }; }
